Add support for Goutte 4
minkphp/MinkGoutteDriver pull request #91
Opened 2021-12-10 20:32 UTC by johnpbloch

Related to #80 and #85.

This adds goutte 4 to the list of versions that satisfy this package's
requirements and updates the driver's implementation to account for the
new version's updates. Since the client in v4 is just an unmodified
extension of HttpBrowser from browserkit, the driver can just defer to
the BrowserKitDriver's implementation.

I ran the test suite with PHP 7.4 and 8.0 and with goutte 3.3 and 4.0 with no failing tests, but we'll see what the tests for the PR say here 😅

2021-12-11 09:45 UTC, stof commented on src/GoutteDriver.php
> +    protected function isClientHttpBrowser()
should be a private method

2021-12-11 09:47 UTC, aik099 commented
This is a more on-topic change than #89.

2021-12-11 09:48 UTC, aik099 requested changes
Looks good, but I'm not sure why PHP 7.1 build always fails. I've tried re-running the build and it still fails.

2021-12-11 09:48 UTC, aik099 commented on src/GoutteDriver.php
> +        }
Please add an empty line after IF.

2021-12-11 09:48 UTC, aik099 commented on src/GoutteDriver.php
> +        if (!$this->isClientHttpBrowser()) {
Please add an empty line before IF.

2021-12-11 23:39 UTC, johnpbloch commented
> Looks good, but I'm not sure why PHP 7.1 build always fails. I've tried re-running the build and it still fails.

It certainly is a puzzling development, especially since 5.4-7.0 still pass.

2021-12-13 09:36 UTC, aik099 commented
@johnpbloch , if you don't have PHP 7.1 installed locally you can try SSHing into GitHub action and see what's going on: https://github.com/marketplace/actions/debugging-with-tmate

Just add this step before running tests and see build log for SSH access credentials

```yaml
- name: Setup tmate session
   if: "${{ matrix.php == '7.1' }}"
   uses: mxschmitt/action-tmate@v3
```

2021-12-13 14:48 UTC, johnpbloch commented
Ok, I've tested on a forge server that has 7.1 and 8.0 and it's actually a problem with the mink test server. I'm not sure why, but the test server segfaults on PHP 7.1. If I run the mink test server with 8.0, the tests all run and pass.

2021-12-13 15:13 UTC, stof commented
There is a known segfault on PHP 7.1 when the timezone is not set in php.ini (see the comment in our GitHub Actions config). Maybe there's another one.

2021-12-13 15:24 UTC, johnpbloch commented
That could be. I'll dig a little more. The tests run fine on master, so it's definitely related to _something_ introduced in this PR, perhaps due to the differences in composer packages?

2021-12-13 15:35 UTC, stof commented
yeah, it could be related to changes in the driver-testsuite that trigger a new case of segfault

2021-12-13 16:18 UTC, johnpbloch commented
Ok, after becoming more familiar with the workflow, I added `symfony/error-handler` to dev dependencies and manually ran the test server with the ini settings in the workflow:
```
php7.1 -d date.timezone=Europe/Paris -d error_reporting=-1 -d display_errors=On -S "localhost:8002" -t vendor/mink/driver-testsuite/web-fixtures
```
and the tests passed, no segfault.

2021-12-13 16:36 UTC, johnpbloch commented
Stranger and stranger: for some reason, alternative timezones also segfault. `America/New_York` and `America/Chicago` both segfault, and so does `UTC`.

2021-12-23 16:47 UTC, stof commented
Closing in favor of #93

2021-12-23 16:47 UTC, closed without merging